Anikin Oleg (Lw1)
wrager/web pull request #10
Opened 2017-03-03 09:29 UTC by AniSkyWorker

2017-03-17 09:30 UTC, wrager requested changes
Замечания

2017-03-17 09:30 UTC, wrager commented on lw1/anikin_oleg/css/styles.css
> +	color: #FFFFFF;
Вместо табов используйте 4 пробела

2017-03-17 09:30 UTC, wrager commented on lw1/anikin_oleg/css/styles.css
> +{
Либо всегда переносите `{`, либо никогда не переносите

2017-03-20 21:05 UTC, AniSkyWorker commented
исправил замечания

2017-03-24 09:17 UTC, wrager approved these changes

2017-03-24 09:18 UTC, merged