Add labWork1
wrager/web pull request #11
Opened 2017-03-03 10:19 UTC by Coguar

2017-03-17 09:40 UTC, wrager requested changes
Замечания

2017-03-17 09:40 UTC, wrager commented on index.html
> +<!-- saved from url=(0076)file:///C:/Users/%D0%A1%D1%82%D0%B5%D0%BF%D0%B0%D0%BD/Desktop/web/index.html -->
Это что?

2017-03-17 09:40 UTC, wrager commented on index.html
> +    <header></header>
Это зачем?

2017-03-17 09:40 UTC, wrager commented on index.html
> +            <span>Нажимая кнопку «Зарегистрироваться», я принимаю условия <a href="https://yandex.ru/legal/rules/" class="reference">Пользовательского соглашения</a> и даю своё согласие Яндексу на об
`«` заменяем на `&laquo;`, `»` - на `&raquo;`

2017-03-17 09:40 UTC, wrager commented on index_files/style.css
> +body {
Зачем этот файл?

2017-03-17 09:40 UTC, wrager commented on index_files/style.css
> +.layout {}
?

2017-03-17 09:40 UTC, wrager commented on index_files/style.css
> +header {}
?

2017-03-17 09:40 UTC, wrager commented on style.css
> +header {}
?

2017-03-17 09:40 UTC, wrager commented on style.css
> +    /* Old browsers */
Комменты убираем

2017-03-17 09:40 UTC, wrager commented on style.css
> +    /* Old browsers */
Комменты убираем

2017-04-28 09:40 UTC, Coguar commented
Исправил замечания

2017-05-15 22:22 UTC, wrager approved these changes

2017-05-15 22:24 UTC, merged