Первая лабораторная(верстка сайта travelline)
wrager/web pull request #20
Opened 2017-03-14 05:49 UTC by cher-cher

Первая лабораторная(верстка сайта travelline)

2017-03-14 06:23 UTC, wrager requested changes
Замечания

2017-03-14 06:23 UTC, wrager commented on lab1/index.html
> +					<p>Стандрт онлайн-продаж</p>
Стандарт

2017-03-14 06:23 UTC, wrager commented on lab1/index.html
> +					<li><a href='#'>Больше броней</a></li>
В HTML для объявления атрибутов используем двойные кавычки

2017-03-14 06:23 UTC, wrager commented on lab1/css/styles.css
> +@import url(reset.css);
URL'ы в стилях всегда оборачиваем в кавычки

2017-03-14 06:23 UTC, wrager commented on lab1/css/styles.css
> +	display: block;
Все табы замени на 2 или 4 пробела

2017-03-14 06:36 UTC, cher-cher commented
исправлены замечания

2017-03-17 08:03 UTC, wrager approved these changes

2017-03-17 08:05 UTC, merged