Васильев Андрей lw1 (4)
wrager/web pull request #4
Opened 2017-02-24 00:33 UTC by dlxgit

2017-02-26 16:39 UTC, wrager requested changes
Нужны исправления + посмотреть на паре

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/index.html
> +                     &#8234;Русский&#8234;
Лишний пробел в отступе

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    src: url(../fonts/font3.ttf) format('truetype');
Хорошая практика - это оборачивать url'ы в стилях в кавычки, т.к. свойство принимает не все символы

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +.header-slogan {
https://translate.google.ru/#ru/en/%D1%81%D0%BB%D0%BE%D0%B3%D0%B0%D0%BD

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    font-family: 'kek';
LOL

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    text-decoration: none;
Не реализовано наведенное состояние у ссылок

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    transition: opacity 0.075s;
Это зачем?

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +.email-input {
У инпута не реализованы ни `:hover`, ни `:focus`

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    transition: all 0.218s;
А это зачем?

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/index.html
> +            <div class="user-img">
В `user-img` у вас находится только картинка, зачем пихать сюда и поле ввода, и кнопку, и ссылку? Даже в инспекторе у этого элемента границы четко по границам картинки, а содержимое, получается, вылезло за эти границы

2017-02-26 16:39 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    font-weight: 500px;
`font-weight` не задается в пикселях, это свойство не сработает
http://htmlbook.ru/css/font-weight

2017-02-28 05:31 UTC, wrager requested changes
Ещё замечания + посмотреть на паре

2017-02-28 05:31 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
>      color: #578DEE;
Цвет переопределяется в то же самое значение?

2017-02-28 05:31 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +.email-input:focus {
Focused состояние не совпадает. Уберите стандартный браузерный `outline`

2017-02-28 05:31 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    transition: all 0.218s;
Жду ответа

2017-02-28 05:31 UTC, wrager commented on lw1/Vasilyev_Andrey/styles/style.css
> +    color: #578DEE;
В оригинале у кнопки не сплошной цвет, а градиент. Странно, стили `.next-btn:hover` скопировали, а стили без ховера - нет

2017-03-10 09:55 UTC, wrager commented
Замечания исправлены не все. Ответ про `transition` не увидел

2017-03-11 15:04 UTC, dlxgit commented on lw1/Vasilyev_Andrey/styles/style.css
>      color: #578DEE;
transition скопировал в самом начале когда делал первые шаги, что-то не работало

2017-03-17 08:47 UTC, wrager approved these changes

2017-03-17 08:47 UTC, merged