Васильев Андрей lw2
wrager/web pull request #8
Opened 2017-03-01 16:26 UTC by dlxgit

2017-03-04 14:00 UTC, dlxgit commented
исправил все замечания

2017-03-17 09:19 UTC, wrager requested changes
Замечания

2017-03-17 09:19 UTC, wrager commented on lw2/Vasilyev_Andrey/index.html
> +    <div class='block'>
Все кавычки сделайте двойными

2017-03-17 09:19 UTC, wrager commented on lw1/Vasilyev_Andrey/index.html
> +<!DOCTYPE html>
Удалите файлы первой лабы

2017-03-17 09:19 UTC, wrager commented on lw2/Vasilyev_Andrey/index.html
> +            <label for='circle-x'>x</label><input id='circle-x' onchange='onCalculateResult()'>
X не обрабатывается

2017-03-17 09:37 UTC, wrager approved these changes

2017-03-17 09:40 UTC, wrager requested changes
Ещё замечание

2017-03-17 09:40 UTC, wrager commented on lw2/Vasilyev_Andrey/index.html
> +    <div class='block'>
Кавычки

2017-04-07 10:07 UTC, wrager approved these changes

2017-04-07 10:08 UTC, merged